<?php

namespace App\Repositories;

use Prettus\Repository\Eloquent\BaseRepository;
use Prettus\Repository\Criteria\RequestCriteria;
use App\Repositories\AthletePartyRepository;
use App\Entities\AthleteParty;
use App\Validators\AthletePartyValidator;

/**
 * Class AthletePartyRepositoryEloquent.
 *
 * @package namespace App\Repositories;
 */
class AthletePartyRepositoryEloquent extends BaseRepository implements AthletePartyRepository
{
    /**
     * Specify Model class name
     *
     * @return string
     */
    public function model()
    {
        return AthleteParty::class;
    }

    

    /**
     * Boot up the repository, pushing criteria
     */
    public function boot()
    {
        $this->pushCriteria(app(RequestCriteria::class));
    }


    public function presenter()
    {
        return "Prettus\\Repository\\Presenter\\ModelFractalPresenter";// TODO: Change the autogenerated stub
    }
    
}
