<?php

namespace App\Repositories;

use Prettus\Repository\Eloquent\BaseRepository;
use Prettus\Repository\Criteria\RequestCriteria;
use App\Repositories\AthleteRepository;
use App\Entities\Athlete;
use App\Validators\AthleteValidator;

/**
 * Class AthleteRepositoryEloquent.
 *
 * @package namespace App\Repositories;
 */
class AthleteRepositoryEloquent extends BaseRepository implements AthleteRepository
{
    /**
     * Specify Model class name
     *
     * @return string
     */
    public function model()
    {
        return Athlete::class;
    }

    

    /**
     * Boot up the repository, pushing criteria
     */
    public function boot()
    {
        $this->pushCriteria(app(RequestCriteria::class));
    }


    public function presenter()
    {
        return "Prettus\\Repository\\Presenter\\ModelFractalPresenter";// TODO: Change the autogenerated stub
    }
}
