<?php

namespace App\Repositories;

use Prettus\Repository\Eloquent\BaseRepository;
use Prettus\Repository\Criteria\RequestCriteria;
use App\Repositories\PartyRepository;
use App\Entities\Party;
use App\Validators\PartyValidator;

/**
 * Class PartyRepositoryEloquent.
 *
 * @package namespace App\Repositories;
 */
class PartyRepositoryEloquent extends BaseRepository implements PartyRepository
{
    /**
     * Specify Model class name
     *
     * @return string
     */
    public function model()
    {
        return Party::class;
    }

    

    /**
     * Boot up the repository, pushing criteria
     */
    public function boot()
    {
        $this->pushCriteria(app(RequestCriteria::class));
    }



    public function presenter()
    {
        return "Prettus\\Repository\\Presenter\\ModelFractalPresenter";// TODO: Change the autogenerated stub
    }
}
